### ISSUE TITLE
Change the class name of Event to avoid conflict with built in event class

### ISSUE THREAD

**Issue by mew2ub** [icyphy/reactor-ts#45]

**Comment by lhstrh** [comment]
What do we call it? How about `TaggedEvent`?

**Comment by Soroosh129** [comment]
How about PEvent for priority event? From: Marten LohstrohSent: Thursday, April 23, 2020 11:12 PMTo: icyphy/reactor-tsCc: SubscribedSubject: Re: [icyphy/reactor-ts] Change the class name of Event to avoid conflict with built in event class (#45) What do we call it? How about TaggedEvent?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Soroosh129** [comment]
First lesson is to not use Windows Mail to reply to messages! Sorry about the garbled reply!

**Comment by mew2ub** [comment]
Yeah I could go for that. The class is basically a wrapper for tags as PrioritySetNodes.
